version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: trully-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: trullygiveaway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vF72HBUWL3)!
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: trully-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: senha_forte_aqui
    ports:
      - "127.0.0.1:5050:80" # s√≥ local
    depends_on:
      - db
    networks:
      - internal

  api:
    build: .
    container_name: trully-api
    command: npm run start:dev
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/trullygiveaway?schema=public
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
    name: gamerdubrasil_pgdata
  api_node_modules:
